import { askRollMode, rollSuccess } from '../helpers/success.mjs';

// Actors whose basic abilities are currently being created, so that several
// sheet renders in a row don't create them twice.
const creatingBasics = new Set();

/**
 * Extend the base Actor document by defining a custom roll data structure which is ideal for the Simple system.
 * @extends {Actor}
 */
export class NoQuarterActor extends Actor {
  /**
   * Augment the actor's default getRollData() method by appending the data object
   * generated by its DataModel's getRollData(), or null. Derived data such as
   * success chances is calculated in the DataModels (module/data), so it is
   * available both inside and outside of character sheets.
   * @override
   */
  getRollData() {
    return { ...super.getRollData(), ...(this.system.getRollData?.() ?? null) };
  }

  /**
   * Whether the wound rules apply: always for characters, and only for the
   * monsters that opt in (bosses).
   * @type {boolean}
   */
  get usesWounds() {
    return this.type === 'character' || !!this.system.usesWounds;
  }

  /**
   * When health reaches 0 a character (or a boss that uses wounds) gains a
   * wound and health resets to its
   * maximum, then any damage beyond 0 is applied to the new health. Handled
   * here so it applies however the health change was made.
   * @override
   */
  async _preUpdate(changes, options, user) {
    const allowed = await super._preUpdate(changes, options, user);
    if (allowed === false) return false;

    let health = foundry.utils.getProperty(changes, 'system.health.value');
    if (health === undefined || health > 0) return;

    const max = this.system.health?.max;
    const usesWounds =
      this.type === 'character' ||
      (foundry.utils.getProperty(changes, 'system.usesWounds') ?? this.system.usesWounds);

    // Without wounds (or with no maximum health to reset to) health stops at 0
    // and the actor is dead; see syncDeath().
    if (!usesWounds || !(max > 0)) {
      foundry.utils.setProperty(changes, 'system.health.value', 0);
      return;
    }

    let gained = 0;
    while (health <= 0) {
      gained++;
      health += max;
    }
    const wounds = foundry.utils.getProperty(changes, 'system.wounds') ?? this.system.wounds;
    foundry.utils.setProperty(changes, 'system.health.value', health);
    foundry.utils.setProperty(changes, 'system.wounds', wounds + gained);
  }

  /**
   * Token bars clamp damage at 0, which would lose the overflow that carries
   * over after a wound. Apply health damage unclamped so `_preUpdate` can
   * handle it.
   * @override
   */
  async modifyTokenAttribute(attribute, value, isDelta = false, isBar = true) {
    if (attribute === 'health' && isBar && isDelta && value < 0) {
      const updates = { 'system.health.value': this.system.health.value + value };
      const allowed = Hooks.call(
        'modifyTokenAttribute',
        { attribute, value, isDelta, isBar },
        updates,
        this
      );
      return allowed !== false ? this.update(updates) : this;
    }
    return super.modifyTokenAttribute(attribute, value, isDelta, isBar);
  }

  /** @override */
  _onUpdate(changed, options, userId) {
    super._onUpdate(changed, options, userId);
    // Death depends on health, wounds and maximum health, so re-check when
    // any of them could have changed.
    const system = changed.system ?? {};
    const relevant = ['wounds', 'stats', 'health', 'usesWounds'];
    if (userId === game.user.id && relevant.some((k) => k in system)) {
      this.syncDeath();
    }
  }

  /**
   * With wounds, an actor is dead once its wounds equal its maximum health.
   * Without them, it is dead once its health reaches 0. Applies or removes the
   * Dead status to match.
   * @returns {Promise<void>}
   */
  async syncDeath() {
    const { health, wounds } = this.system;
    const dead = this.usesWounds ? health.max > 0 && wounds >= health.max : health.value <= 0;
    if (dead === this.statuses.has(CONFIG.specialStatusEffects.DEFEATED)) return;
    await this.toggleStatusEffect(CONFIG.specialStatusEffects.DEFEATED, {
      active: dead,
      overlay: dead,
    });
  }

  /** @override */
  _onCreate(data, options, userId) {
    super._onCreate(data, options, userId);
    if (userId === game.user.id) this.ensureBasicAbilities();
  }

  /**
   * Give a character any of the basic abilities it is missing.
   * @returns {Promise<void>}
   */
  async ensureBasicAbilities() {
    if (this.type !== 'character' || !this.isOwner) return;
    if (creatingBasics.has(this.id)) return;

    const have = new Set(
      this.items
        .filter((i) => i.type === 'ability' && i.system.basicKey)
        .map((i) => i.system.basicKey)
    );
    const missing = Object.entries(CONFIG.NOQUARTER.basicAbilities)
      .map(([key, basic], index) => ({ key, basic, index }))
      .filter(({ key }) => !have.has(key));
    if (!missing.length) return;

    creatingBasics.add(this.id);
    try {
      await this.createEmbeddedDocuments(
        'Item',
        missing.map(({ key, basic, index }) => ({
          name: game.i18n.localize(basic.name),
          type: 'ability',
          sort: index * 10,
          system: {
            basicKey: key,
            stat: basic.stat,
            rank: 0,
            staminaCost: 0,
          },
        }))
      );
    } finally {
      creatingBasics.delete(this.id);
    }
  }

  /**
   * Make every limited-use ability available again, at the end of a combat.
   * @returns {Promise<void>}
   */
  async resetAbilityUses() {
    const updates = this.items
      .filter((i) => i.type === 'ability' && i.system.used > 0)
      .map((i) => ({ _id: i.id, 'system.used': 0 }));
    if (updates.length) await this.updateEmbeddedDocuments('Item', updates);
  }

  /**
   * Roll d100 against one of the actor's stats (or a monster's single set of
   * chances) and post the result.
   * @param {string} key   The stat key, such as "might"
   * @returns {Promise<Roll|undefined>}
   */
  async rollStat(key) {
    // A monster has a single set of chances instead of individual stats.
    if (this.type === 'npc') {
      const label = game.i18n.localize('NOQUARTER.Check');
      const chances = this.system.chances;
      const mode = await askRollMode({ label, chances });
      if (!mode) return;
      return rollSuccess({ actor: this, label, chances, mode });
    }

    const stat = this.system.stats?.[key];
    if (!stat) return;

    const label = game.i18n.localize(CONFIG.NOQUARTER.stats[key]);
    const mode = await askRollMode({ label, chances: stat.target });
    if (!mode) return;
    return rollSuccess({
      actor: this,
      label,
      chances: stat.target,
      mode,
    });
  }
}
